version: '3'
services:
  chat_mongo:
    container_name: chat_mongo
    image: mongo:4.0.4
    ports:
     - "27017:27017"
     - "28017:28017"
  mongo_seed:
    container_name: mongo_seed
    build: ./mongodb
    image: mongo_seed:0-0-1
    links:
      - chat_mongo